/*
 * Copyright (c) 2026 Daphne Pfister
 * SPDX-License-Identifier: BSD-2-Clause
 * See LICENSE file for full license text
 */

//! Proc-macro support crate for `schedule-core`.
//!
//! Currently provides four function-like proc-macros:
//!
//! - [`define_field`] — declarative `FieldDescriptor` static + inventory
//!   submission.  Branches on parameter shape:
//!   - `accessor: <ident>` — stored field (auto crdt + read/write from accessor)
//!   - `edge: ro|rw|one|add|remove` — edge field (auto crdt from `owner` flag,
//!     auto read/write from edge mode; supports `exclusive_with: &SIBLING_FIELD`)
//!   - neither — custom field; require explicit `crdt:`, `cardinality:`,
//!     `item:`, and at least one of `read:` / `write:` closures.
//!   - `name:`, `display:`, `desc:`, `aliases:`, `example:`, `order:`, `required` flag,
//!   - optional `read:` / `write:` closures (override auto-generated).
//!
//! For manual field and edge descriptors, callbacks can be generated by the following
//! macros which take the parameters specific to the field type, along with most of
//! `CommonFieldData` parameters with the exception of `field_type` and `crdt_type`
//!
//! - [`accessor_field_properties`] — generates `(CommonFieldData, FieldCallbacks)`
//!   tuple for accessor-based fields without custom callbacks.
//!
//! - [`edge_field_properties`] — generates `(CommonFieldData, FieldCallbacks, EdgeKind)`
//!   tuple for edge fields without custom callbacks.
//!
//! - [`callback_field_properties`] — generates `(CommonFieldData, FieldCallbacks)`
//!   tuple for fields with custom callbacks (closures or enum variants).
//!
//! Re-exported from `schedule-core` so callers `use schedule_core::define_field;`.

mod callback_input;
mod callback_output;
mod common_input;
mod common_output;
mod edge_input;
mod edge_output;
mod input;
mod output;
mod stored_input;
mod stored_output;

use proc_macro::TokenStream;

/// See crate-level documentation.
#[proc_macro]
pub fn define_field(input: TokenStream) -> TokenStream {
    let parsed = syn::parse_macro_input!(input as input::FieldInput);
    match output::expand(&parsed) {
        Ok(ts) => ts.into(),
        Err(e) => e.to_compile_error().into(),
    }
}

/// Generate `CommonFieldData` and `FieldCallbacks` for an accessor-based field.
///
/// Returns a `(CommonFieldData, FieldCallbacks<E>)` tuple containing both
/// the field metadata and the read/write/add/remove callbacks inferred from
/// the field's cardinality and item type. The caller constructs the
/// `FieldDescriptor` to control `required`, `edge_kind`, and other
/// descriptor-level properties.
///
/// # Syntax
///
/// ```ignore
/// let (data, cb) = accessor_field_properties! {
///     EntityType,
///     accessor_name,
///     name: "field_name",
///     display: "Field Name",
///     description: "Description text",
///     aliases: &["alias1", "alias2"],
///     cardinality: Single | Optional | List,
///     item: String | Boolean | Integer | Float | DateTime | Duration | Text,
///     example: "example value",
///     order: 100,
///     [required: true | false,]
/// };
/// ```
///
/// The `required` parameter is optional and defaults to `true` for `Single`
/// cardinality and `false` for `Optional` or `List`.
///
/// # Example
///
/// ```ignore
/// pub static FIELD_PREFIX: FieldDescriptor<PanelTypeEntityType> = {
///     let (data, cb) = accessor_field_properties! {
///         PanelTypeEntityType,
///         prefix,
///         name: "prefix",
///         display: "Prefix",
///         description: "Two-letter Uniq ID prefix for panels of this type.",
///         aliases: &["uniq_id_prefix"],
///         cardinality: Single,
///         item: String,
///         example: "GP",
///         order: 0,
///     };
///     FieldDescriptor {
///         data,
///         required: true,
///         edge_kind: EdgeKind::NonEdge,
///         cb,
///     }
/// };
/// inventory::submit! { CollectedNamedField(&FIELD_PREFIX) }
/// ```
#[proc_macro]
pub fn accessor_field_properties(input: TokenStream) -> TokenStream {
    let parsed = syn::parse_macro_input!(input as stored_input::StoredInput);
    match stored_output::expand(&parsed) {
        Ok(ts) => ts.into(),
        Err(e) => e.to_compile_error().into(),
    }
}

/// Generate `CommonFieldData`, `FieldCallbacks`, and `EdgeKind` for an edge field.
///
/// Returns a `(CommonFieldData, FieldCallbacks<E>, EdgeKind)` tuple containing
/// the field metadata, read/write/add/remove callbacks, and edge ownership information.
/// The caller constructs the `FieldDescriptor` to control other descriptor-level
/// properties.
///
/// Supports both owner edges (with optional exclusivity) and target edges (with
/// multiple source fields).
///
/// # Owner edge syntax
///
/// ```ignore
/// let (data, cb, edge_kind) = edge_field_properties! {
///     EntityType,
///     target: TargetEntityType,
///     target_field: &other_entity::FIELD_OTHER,
///     [exclusive_with: &FIELD_SIBLING,]
///     name: "field_name",
///     display: "Field Name",
///     description: "Description text",
///     aliases: &["alias1", "alias2"],
///     example: "example value",
///     order: 100,
/// };
/// ```
///
/// # Target edge syntax
///
/// ```ignore
/// let (data, cb, edge_kind) = edge_field_properties! {
///     EntityType,
///     target: TargetEntityType,
///     source_fields: &[&other_entity::FIELD_OWNER1, &other_entity::FIELD_OWNER2],
///     name: "field_name",
///     display: "Field Name",
///     description: "Description text",
///     aliases: &["alias1", "alias2"],
///     example: "example value",
///     order: 100,
/// };
/// ```
///
/// # Owner edge example
///
/// ```ignore
/// pub static FIELD_CREDITED_PRESENTERS: FieldDescriptor<PanelEntityType> = {
///     let (data, cb, edge_kind) = edge_field_properties! {
///         PanelEntityType,
///         target: PresenterEntityType,
///         target_field: &crate::tables::presenter::FIELD_PANELS,
///         exclusive_with: &FIELD_UNCREDITED_PRESENTERS,
///         name: "credited_presenters",
///         display: "Credited Presenters",
///         description: "Presenters credited on this panel.",
///         aliases: &["credited_panelists", "credited_presenter"],
///         example: "[presenter_id]",
///         order: 2710,
///     };
///     FieldDescriptor {
///         data,
///         required: false,
///         edge_kind,
///         cb,
///     }
/// };
/// inventory::submit! { CollectedNamedField(&FIELD_CREDITED_PRESENTERS) }
/// ```
#[proc_macro]
pub fn edge_field_properties(input: TokenStream) -> TokenStream {
    let parsed = syn::parse_macro_input!(input as edge_input::EdgeInput);
    match edge_output::expand(&parsed) {
        Ok(ts) => ts.into(),
        Err(e) => e.to_compile_error().into(),
    }
}

/// Generate `CommonFieldData` and `FieldCallbacks` with custom callbacks.
///
/// Returns a `(CommonFieldData, FieldCallbacks<E>)` tuple containing both
/// the field metadata and the specified callbacks. The caller constructs the
/// `FieldDescriptor` or `EdgeDescriptor` to control other descriptor-level
/// properties.
///
/// This macro is useful when you need custom callback behavior that differs
/// from the auto-generated behavior of `accessor_field_properties!` or
/// `edge_field_properties!`.
///
/// # Syntax
///
/// ```ignore
/// let (data, cb) = callback_field_properties! {
///     EntityType,
///     name: "field_name",
///     display: "Field Name",
///     description: "Description text",
///     aliases: &["alias1", "alias2"],
///     cardinality: Single | Optional | List,
///     item: String | Boolean | Integer | Float | DateTime | Duration | Text,
///     example: "example value",
///     order: 100,
///     [read: <closure or enum variant>,]
///     [write: <closure or enum variant>,]
///     [add: <closure or enum variant>,]
///     [remove: <closure or enum variant>,]
/// };
/// ```
///
/// The callback parameters are optional. If not provided, they default to `None`.
/// Callbacks can be either closures or enum variants.
///
/// **Closures**: Detected by leading `|` or `move |`. The macro automatically
/// wraps closures in the appropriate enum variant based on arity:
/// - Read closures: 1 arg → `ReadFn::Bare`, 2 args → `ReadFn::Schedule`
/// - Write closures: 2 args → `WriteFn::Bare`, 3 args → `WriteFn::Schedule`
/// - Add closures: 2 args → `AddFn::Bare`, 3 args → `AddFn::Schedule`
/// - Remove closures: 2 args → `RemoveFn::Bare`, 3 args → `RemoveFn::Schedule`
///
/// **Enum variants**: Use directly without wrapping, e.g.:
/// - `ReadFn::ReadEdge`
/// - `WriteFn::WriteEdge`
/// - `WriteFn::AddEdge { edge, exclusive_with }`
/// - `WriteFn::RemoveEdge { edge }`
/// - `AddFn::AddEdge`
/// - `RemoveFn::RemoveEdge`
///
/// # Example
///
/// ```ignore
/// pub static FIELD_CUSTOM: FieldDescriptor<PanelEntityType> = {
///     let (data, cb) = callback_field_properties! {
///         PanelEntityType,
///         name: "custom_field",
///         display: "Custom Field",
///         description: "A field with custom callbacks.",
///         aliases: &[],
///         cardinality: Optional,
///         item: String,
///         example: "example",
///         order: 100,
///         read: ReadFn::ReadEdge,
///         write: WriteFn::WriteEdge,
///     };
///     FieldDescriptor {
///         data,
///         required: false,
///         edge_kind: EdgeKind::NonEdge,
///         cb,
///     }
/// };
/// inventory::submit! { CollectedNamedField(&FIELD_CUSTOM) }
/// ```
#[proc_macro]
pub fn callback_field_properties(input: TokenStream) -> TokenStream {
    let parsed = syn::parse_macro_input!(input as callback_input::CallbackInput);
    match callback_output::expand(&parsed) {
        Ok(ts) => ts.into(),
        Err(e) => e.to_compile_error().into(),
    }
}
