/*
 * Copyright (c) 2026 Daphne Pfister
 * SPDX-License-Identifier: BSD-2-Clause
 * See LICENSE file for full license text
 */

//! Entity system with type-safe field operations.
//!
//! Each entity type (Panel, Presenter, Room, PanelType, Edge) is defined as a
//! plain Rust struct that derives [`EntityFields`](crate::EntityFields).  The
//! derive macro generates:
//!
//! - Per-field unit structs implementing [`NamedField`](crate::field::traits::NamedField),
//!   [`SimpleReadableField`](crate::field::traits::SimpleReadableField), and
//!   [`SimpleWritableField`](crate::field::traits::SimpleWritableField)
//! - A `<Name>Data` internal storage struct with stored fields plus `entity_uuid: uuid::Uuid`
//! - A separate [`EntityType`] struct (e.g., `PanelEntityType`) with `impl EntityType for PanelEntityType`
//!   where `type Data = PanelData`
//! - A static [`FieldSet`](crate::field::field_set::FieldSet) accessible via
//!   `PanelEntityType::field_set()`
//!
//! ## Identifiers
//!
//! All entity instances are identified by [`uuid::Uuid`] v4.  Per-entity typed
//! wrappers (e.g. `PanelId(Uuid)`) provide compile-time type safety for public
//! APIs.
//!
//! ## Re-exports
//!
//! Entity types are re-exported explicitly (not via glob) to avoid name
//! collisions from macro-generated field structs like `NameField`,
//! `IsBreakField`, etc.

pub mod event_room;
pub mod hotel_room;
pub mod panel;
pub mod panel_type;
pub mod presenter;
pub mod presenter_rank;

// Re-export public entity types (explicit to avoid ambiguous glob re-exports
// from macro-generated field structs like NameField, IsBreakField, etc.)
pub use event_room::EventRoom;
pub use hotel_room::HotelRoom;
pub use panel::Panel;
pub use panel_type::PanelType;
pub use presenter::Presenter;
pub use presenter_rank::PresenterRank;

// Re-export typed entity ID wrappers
pub use event_room::EventRoomId;
pub use hotel_room::HotelRoomId;
pub use panel::PanelId;
pub use panel_type::PanelTypeId;
pub use presenter::PresenterId;

// Re-export EntityType structs for clean import paths
pub use event_room::EventRoomEntityType;
pub use hotel_room::HotelRoomEntityType;
pub use panel::PanelEntityType;
pub use panel_type::PanelTypeEntityType;
pub use presenter::PresenterEntityType;

pub use uuid::Uuid;

// Re-export internal Data structs used elsewhere in the crate
pub(crate) use event_room::EventRoomData;
pub(crate) use hotel_room::HotelRoomData;
pub(crate) use panel::PanelData;
pub(crate) use panel_type::PanelTypeData;
pub(crate) use presenter::PresenterData;

use std::fmt;

use crate::field::field_set::FieldSet;
use crate::field::validation::ValidationError;

/// Trait for all internal entity data structs generated by the macro.
/// Guarantees that every entity data struct carries its own UUID.
pub trait InternalData: Clone + Send + Sync + fmt::Debug {
    fn uuid(&self) -> Uuid;
    fn set_uuid(&mut self, id: Uuid);
}

/// Core trait for all entity types
pub trait EntityType: 'static + Send + Sync + fmt::Debug {
    type Data: InternalData;
    // @todo: type PublicData: PublicData;

    const TYPE_NAME: &'static str;
    const KIND: EntityKind;

    fn field_set() -> &'static FieldSet<Self>
    where
        Self: Sized;
    fn validate(data: &Self::Data) -> Result<(), ValidationError>
    where
        Self: Sized;

    /// Get the type name for this entity type (for dyn compatibility)
    fn type_name(&self) -> &'static str {
        Self::TYPE_NAME
    }

    /// Get the EntityKind for this entity type
    fn kind() -> EntityKind
    where
        Self: Sized,
    {
        Self::KIND
    }
}

/// Marker trait for entities that can be scheduled (assigned to panel types and event rooms)
pub trait SchedulableEntity: EntityType {}

/// Entity state for soft delete and status tracking
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum EntityState {
    Active,
    Inactive,
}

impl Default for EntityState {
    fn default() -> Self {
        Self::Active
    }
}

/// Identifies which entity type a UUID belongs to, used by the schedule's UUID registry.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum EntityKind {
    Panel,
    Presenter,
    EventRoom,
    HotelRoom,
    PanelType,
}

/// Owned public entity value returned by `Schedule::fetch_uuid`.
#[derive(Debug, Clone)]
pub enum PublicEntityRef {
    Panel(Panel),
    Presenter(Presenter),
    EventRoom(EventRoom),
    HotelRoom(HotelRoom),
    PanelType(PanelType),
}

/// Borrowed entity data reference returned by `Schedule::lookup_uuid`.
#[derive(Debug, Clone, Copy)]
pub enum EntityRef<'a> {
    Panel(&'a PanelData),
    Presenter(&'a PresenterData),
    EventRoom(&'a EventRoomData),
    HotelRoom(&'a HotelRoomData),
    PanelType(&'a PanelTypeData),
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn entity_kind_copy_and_eq() {
        let kind = EntityKind::Panel;
        let copy = kind;
        assert_eq!(kind, copy);
    }

    #[test]
    fn entity_kind_all_variants() {
        let variants = [
            EntityKind::Panel,
            EntityKind::Presenter,
            EntityKind::EventRoom,
            EntityKind::HotelRoom,
            EntityKind::PanelType,
        ];
        assert_eq!(variants.len(), 5);
    }
}
