/*
 * Copyright (c) 2026 Daphne Pfister
 * SPDX-License-Identifier: BSD-2-Clause
 * See LICENSE file for full license text
 */

//! Entity system with type-safe field operations.
//!
//! Each entity type (Panel, Presenter, Room, PanelType, Edge) is defined as a
//! plain Rust struct that derives [`EntityFields`](crate::EntityFields).  The
//! derive macro generates:
//!
//! - Per-field unit structs implementing [`NamedField`](crate::field::traits::NamedField),
//!   [`SimpleReadableField`](crate::field::traits::SimpleReadableField), and
//!   [`SimpleWritableField`](crate::field::traits::SimpleWritableField)
//! - A `<Name>Data` internal storage struct with stored fields plus `entity_uuid: uuid::NonNilUuid`
//! - A separate [`EntityType`] struct (e.g., `PanelEntityType`) with `impl EntityType for PanelEntityType`
//!   where `type Data = PanelData`
//! - A static [`FieldSet`](crate::field::field_set::FieldSet) accessible via
//!   `PanelEntityType::field_set()`
//!
//! ## Identifiers
//!
//! All entity instances are identified by [`uuid::NonNilUuid`] v4.  Per-entity typed
//! wrappers (e.g. `PanelId(NonNilUuid)`) provide compile-time type safety for public
//! APIs.
//!
//! ## Re-exports
//!
//! Entity types are re-exported explicitly (not via glob) to avoid name
//! collisions from macro-generated field structs like `NameField`,
//! `IsBreakField`, etc.

// Implemented entities
pub mod event_room;
pub mod event_room_to_hotel_room;
pub mod hotel_room;
pub mod panel;
pub mod panel_to_event_room;
pub mod panel_to_panel_type;
pub mod panel_to_presenter;
pub mod panel_type;
pub mod panel_uniq_id;
pub mod presenter;
pub mod presenter_rank;
pub mod presenter_to_group;
pub mod uuid_preference;

// Re-export public entity types (explicit to avoid ambiguous glob re-exports
// from macro-generated field structs like NameField, IsBreakField, etc.)
pub use event_room::EventRoom;
pub use event_room_to_hotel_room::EventRoomToHotelRoom;
pub use hotel_room::HotelRoom;
pub use panel::Panel;
pub use panel_to_event_room::PanelToEventRoom;
pub use panel_to_panel_type::PanelToPanelType;
pub use panel_to_presenter::PanelToPresenter;
pub use panel_type::PanelType;
pub use presenter::Presenter;
pub use presenter_rank::PresenterRank;
pub use presenter_to_group::PresenterToGroup;
pub use uuid_preference::UuidPreference;

// Re-export typed entity ID wrappers
pub use event_room::EventRoomId;
pub use event_room_to_hotel_room::EventRoomToHotelRoomId;
pub use hotel_room::HotelRoomId;
pub use panel::PanelId;
pub use panel_to_event_room::PanelToEventRoomId;
pub use panel_to_panel_type::PanelToPanelTypeId;
pub use panel_to_presenter::PanelToPresenterId;
pub use panel_type::PanelTypeId;
pub use panel_uniq_id::PanelUniqId;
pub use presenter::PresenterId;
pub use presenter::PresenterSortRank;
pub use presenter_to_group::PresenterToGroupId;

// Re-export EntityType structs for clean import paths
pub use event_room::EventRoomEntityType;
pub use event_room_to_hotel_room::EventRoomToHotelRoomEntityType;
pub use hotel_room::HotelRoomEntityType;
pub use panel::PanelEntityType;
pub use panel_to_event_room::PanelToEventRoomEntityType;
pub use panel_to_panel_type::PanelToPanelTypeEntityType;
pub use panel_to_presenter::PanelToPresenterEntityType;
pub use panel_type::PanelTypeEntityType;
pub use presenter::PresenterEntityType;
pub use presenter_to_group::PresenterToGroupEntityType;

pub use uuid::NonNilUuid;

// Re-export Data structs for use by schedule storage and importers
pub use event_room::EventRoomData;
pub use event_room_to_hotel_room::EventRoomToHotelRoomData;
pub use hotel_room::HotelRoomData;
pub use panel::PanelData;
pub use panel_to_event_room::PanelToEventRoomData;
pub use panel_to_panel_type::PanelToPanelTypeData;
pub use panel_to_presenter::PanelToPresenterData;
pub use panel_type::PanelTypeData;
pub use presenter::PresenterData;
pub use presenter_to_group::PresenterToGroupData;

use std::fmt;

use crate::field::field_set::FieldSet;
use crate::field::validation::ValidationError;
use uuid::Uuid;

/// Trait for all internal entity data structs generated by the macro.
/// Guarantees that every entity data struct carries its own UUID.
pub trait InternalData: Clone + Send + Sync + fmt::Debug {
    fn uuid(&self) -> NonNilUuid;
    fn set_uuid(&mut self, id: NonNilUuid);
}

/// Core trait for all entity types
pub trait EntityType: 'static + Send + Sync + fmt::Debug {
    type Data: InternalData;
    type Id: TypedId<EntityType = Self>;

    const TYPE_NAME: &'static str;
    const KIND: EntityKind;

    fn field_set() -> &'static FieldSet<Self>
    where
        Self: Sized;
    fn validate(data: &Self::Data) -> Result<(), ValidationError>
    where
        Self: Sized;

    /// Get the type name for this entity type (for dyn compatibility)
    fn type_name(&self) -> &'static str {
        Self::TYPE_NAME
    }

    /// Get the EntityKind for this entity type
    fn kind() -> EntityKind
    where
        Self: Sized,
    {
        Self::KIND
    }
}

/// Marker trait for entities that can be scheduled (assigned to panel types and event rooms)
pub trait SchedulableEntity: EntityType {}

/// Trait for edge-entities that connect two other entities.
///
/// Implemented by the macro-generated `*Data` structs for edge types such as
/// `PanelToPresenterData`.  `From` and `To` are the [`TypedId`] types for the
/// two endpoint entities, giving callers compile-time access to the correct ID
/// types without any runtime dispatch.
pub trait DirectedEdge {
    /// Typed ID of the source entity (the "from" side).
    type FromId: TypedId;
    /// Typed ID of the destination entity (the "to" side).
    type ToId: TypedId;

    fn from_id(&self) -> Self::FromId;
    fn to_id(&self) -> Self::ToId;

    fn from_uuid(&self) -> NonNilUuid {
        self.from_id().non_nil_uuid()
    }

    fn to_uuid(&self) -> NonNilUuid {
        self.to_id().non_nil_uuid()
    }

    /// Returns `true` when `from` and `to` refer to the same UUID (e.g. group
    /// marker self-loops in `PresenterToGroup`).
    fn is_self_loop(&self) -> bool {
        self.from_uuid() == self.to_uuid()
    }
}

/// Entity state for soft delete and status tracking
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum EntityState {
    #[default]
    Active,
    Inactive,
}

/// Identifies which entity type a UUID belongs to, used by the schedule's UUID registry.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum EntityKind {
    Panel,
    Presenter,
    EventRoom,
    HotelRoom,
    PanelType,
    PanelToPresenter,
    PanelToEventRoom,
    EventRoomToHotelRoom,
    PanelToPanelType,
    PresenterToGroup,
}

/// Trait for typed entity ID wrappers.
/// Provides a uniform interface for all entity IDs backed by `NonNilUuid`.
pub trait TypedId: Copy + Clone + Send + Sync + fmt::Debug + 'static {
    type EntityType: EntityType;

    fn non_nil_uuid(&self) -> NonNilUuid;

    fn uuid(&self) -> Uuid {
        self.non_nil_uuid().into()
    }

    fn kind() -> EntityKind {
        Self::EntityType::KIND
    }

    fn from_uuid(uuid: NonNilUuid) -> Self;

    fn try_from_raw_uuid(uuid: Uuid) -> Option<Self> {
        NonNilUuid::new(uuid).map(Self::from_uuid)
    }
}

/// A `NonNilUuid` tagged with the entity kind it refers to.
/// Returned by `Schedule::identify()`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum EntityUUID {
    EventRoom(EventRoomId),
    EventRoomToHotelRoom(EventRoomToHotelRoomId),
    HotelRoom(HotelRoomId),
    Panel(PanelId),
    PanelToEventRoom(PanelToEventRoomId),
    PanelToPanelType(PanelToPanelTypeId),
    PanelToPresenter(PanelToPresenterId),
    PanelType(PanelTypeId),
    Presenter(PresenterId),
    PresenterToGroup(PresenterToGroupId),
}

impl EntityUUID {
    pub fn non_nil_uuid(&self) -> NonNilUuid {
        match self {
            EntityUUID::EventRoom(id) => id.non_nil_uuid(),
            EntityUUID::EventRoomToHotelRoom(id) => id.non_nil_uuid(),
            EntityUUID::HotelRoom(id) => id.non_nil_uuid(),
            EntityUUID::Panel(id) => id.non_nil_uuid(),
            EntityUUID::PanelToEventRoom(id) => id.non_nil_uuid(),
            EntityUUID::PanelToPanelType(id) => id.non_nil_uuid(),
            EntityUUID::PanelToPresenter(id) => id.non_nil_uuid(),
            EntityUUID::PanelType(id) => id.non_nil_uuid(),
            EntityUUID::Presenter(id) => id.non_nil_uuid(),
            EntityUUID::PresenterToGroup(id) => id.non_nil_uuid(),
        }
    }

    pub fn uuid(&self) -> Uuid {
        self.non_nil_uuid().into()
    }

    pub fn kind(&self) -> EntityKind {
        match self {
            EntityUUID::EventRoom(_) => EntityKind::EventRoom,
            EntityUUID::EventRoomToHotelRoom(_) => EntityKind::EventRoomToHotelRoom,
            EntityUUID::HotelRoom(_) => EntityKind::HotelRoom,
            EntityUUID::Panel(_) => EntityKind::Panel,
            EntityUUID::PanelToEventRoom(_) => EntityKind::PanelToEventRoom,
            EntityUUID::PanelToPanelType(_) => EntityKind::PanelToPanelType,
            EntityUUID::PanelToPresenter(_) => EntityKind::PanelToPresenter,
            EntityUUID::PanelType(_) => EntityKind::PanelType,
            EntityUUID::Presenter(_) => EntityKind::Presenter,
            EntityUUID::PresenterToGroup(_) => EntityKind::PresenterToGroup,
        }
    }
}

/// Owned public entity value returned by `Schedule::fetch_uuid`.
#[derive(Debug, Clone)]
#[allow(clippy::large_enum_variant)]
pub enum PublicEntityRef {
    EventRoom(EventRoom),
    EventRoomToHotelRoom(EventRoomToHotelRoom),
    HotelRoom(HotelRoom),
    Panel(Panel),
    PanelToEventRoom(PanelToEventRoom),
    PanelToPanelType(PanelToPanelType),
    PanelToPresenter(PanelToPresenter),
    PanelType(PanelType),
    Presenter(Presenter),
    PresenterToGroup(PresenterToGroup),
}

/// Borrowed entity data reference returned by `Schedule::lookup_uuid`.
#[derive(Debug, Clone, Copy)]
pub enum EntityRef<'a> {
    EventRoom(&'a EventRoomData),
    EventRoomToHotelRoom(&'a EventRoomToHotelRoomData),
    HotelRoom(&'a HotelRoomData),
    Panel(&'a PanelData),
    PanelToEventRoom(&'a PanelToEventRoomData),
    PanelToPanelType(&'a PanelToPanelTypeData),
    PanelToPresenter(&'a PanelToPresenterData),
    PanelType(&'a PanelTypeData),
    Presenter(&'a PresenterData),
    PresenterToGroup(&'a PresenterToGroupData),
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn entity_kind_copy_and_eq() {
        let kind = EntityKind::Panel;
        let copy = kind;
        assert_eq!(kind, copy);
    }

    #[test]
    fn entity_kind_all_variants() {
        let variants = [
            EntityKind::Panel,
            EntityKind::Presenter,
            EntityKind::EventRoom,
            EntityKind::HotelRoom,
            EntityKind::PanelType,
        ];
        assert_eq!(variants.len(), 5);
    }
}
